#!/bin/bash

cd simulations;
python experiment.py  \
	--numClients 1 \
	--numServers 3 \
	--numWorkload 10 \
	--serverQueueCapacity 1 \
	--serviceTime 4.00 \
	--replicationFactor 3 \
	--selectionStrategy primary \
	--accessPattern uniform \
	--nwLatencyBase 0.00 \
	--nwLatencyMu 0.0 \
	--nwLatencySigma 0.0 \
	--expPrefix primary\
	--simulationDuration 1000;

python experiment.py  \
	--numClients 1 \
	--numServers 3 \
	--numWorkload 10 \
	--serverQueueCapacity 1 \
	--serviceTime 4.00 \
	--replicationFactor 3 \
	--selectionStrategy response_time \
	--accessPattern uniform \
	--nwLatencyBase 0.00 \
	--nwLatencyMu 0.0 \
	--nwLatencySigma 0.0 \
	--expPrefix rp\
	--simulationDuration 1000;

cd ..
cd plotting;
Rscript timeseries.r primary;
Rscript timeseries.r rp;
cd ..
