#!/bin/bash

cd simulations;

# python experiment.py  \
# 	--numClients 60 \
# 	--numServers 10 \
# 	--numWorkload 1 \
# 	--workloadModel constant \
# 	--serverConcurrency 1 \
# 	--serviceTime 4.00\
# 	--utilization 0.85 \
# 	--serviceTimeModel random.expovariate \
# 	--replicationFactor 3 \
# 	--selectionStrategy ds \
# 	--shadowReadRatio 0.0 \
# 	--accessPattern uniform \
# 	--nwLatencyBase 0.00 \
# 	--nwLatencyMu 0.0\
# 	--nwLatencySigma 0.00 \
# 	--expPrefix oracle\
# 	--simulationDuration 50000\
# 	--seed 2\
# 	--numRequests 10000\
# 	--logFolder logs\
# 	--expScenario timeVaryingServiceTimeServers\
# 	--demandSkew 0.0\
# 	--highDemandFraction 0.0\
# 	--slowServerFraction 0.0\
# 	--slowServerSlowness 0.0\
# 	--intervalParam 500\
# 	--timeVaryingDrift 10;

python experiment.py  \
 	--numClients 1 \
	--numServers 2 \
	--numWorkload 1 \
	--workloadModel constant \
	--serverConcurrency 1 \
	--serviceTime 4.00 \
	--utilization 0.85 \
	--serviceTimeModel random.expovariate \
	--replicationFactor 3 \
	--backpressure \
	--rateInterval 20\
	--cubicC 0.000004\
	--cubicSmax 10\
	--cubicBeta 0.2\
	--hysterisisFactor 2\
	--selectionStrategy expDelay \
	--shadowReadRatio 0.0 \
	--accessPattern uniform \
	--nwLatencyBase 0.00 \
	--nwLatencyMu 0.0\
	--nwLatencySigma 0.00 \
	--expPrefix expDelay \
	--simulationDuration 50000 \
	--seed 2 \
	--numRequests 10000\
	--logFolder logs\
	--expScenario base\
	--demandSkew 0\
	--highDemandFraction 0.0\
	--slowServerFraction 0.0\
	--slowServerSlowness 0.0\
	--intervalParam 10000\
	--timeVaryingDrift 10;


cd ..
cd plotting;
# Rscript timeseries.r primary;
# Rscript timeseries.r rp;
# Rscript timeseries.r pending;
# Rscript timeseries.r pendingXserviceTime;
Rscript timeseries.r oracle;
Rscript timeseries.r expDelay;
cd ..
