#!/bin/bash

cd simulations;
python experiment.py  \
	--numClients 5 \
	--numServers 3 \
	--numWorkload 40 \
	--serverQueueCapacity 4 \
	--serviceTime 4.00 \
	--replicationFactor 3 \
	--selectionStrategy response_time \
	--accessPattern uniform \
	--nwLatencyBase 0.300 \
	--nwLatencySigma 0.0 \
	--expPrefix test;
cd ..
cd plotting;
Rscript timeseries.r test;
cd ..
