# These are defaults.
NW_LATENCY_BASE = 0.960
NW_LATENCY_MU = 0.040
NW_LATENCY_SIGMA = 0.0
NUMBER_OF_CLIENTS = 1
PACKET_SIZE = 1
SWITCH_BUFFER_SIZE = 10
CE_UPDATE_PERIOD = 1
CE_WEIGHT = 0.9
READ = 1
WRITE = 2

import logging
LOG_LEVEL = logging.DEBUG
