# These are defaults.
PROPAGATION_DELAY = 0.4
NUMBER_OF_CLIENTS = 1
SWITCH_BUFFER_SIZE = 10
CE_UPDATE_PERIOD = 1
CE_WEIGHT = 0.9
READ = 1
WRITE = 2
BACKGROUND = 1
APP = 2
PACKET_SIZE = 0.001
TARGET_LATENCY = 5
TOPOLOGY = None
MAXREQUESTDELAY = 1000000000
END_SIMULATION = False
BACKGROUND_TRAFFIC_DELAY = 0.001
BACKGROUND_SPAWNING_DELAY = 1
FORWARDING_STRATEGY = "ECMP"
PER_PACKET_FORWARDING = False
TEST_RUN = False

import logging
LOG_LEVEL = logging.DEBUG
