# These are defaults.
NW_LATENCY_BASE = 0.4
NW_LATENCY_MU = 0.040
NW_LATENCY_SIGMA = 0.0
NUMBER_OF_CLIENTS = 1
PACKET_SIZE = 1
SWITCH_BUFFER_SIZE = 10
CE_UPDATE_PERIOD = 1
CE_WEIGHT = 0.9
READ = 1
WRITE = 2
BACKGROUND = 1
APP = 2
PACKET_SIZE = 0.001
TARGET_LATENCY = 5
TOPOLOGY = None
MAXREQUESTDELAY = 1000000000
END_SIMULATION = False
BACKGROUND_SENDING_DELAY = 0.001
BACKGROUND_SPAWNING_INTERARRIVAL = 0.001
TEST_RUN = False

import logging
LOG_LEVEL = logging.DEBUG
